//>>built
require({cache:{"dojo/request/default":function(){define(["exports","require","../has"],function(r,q,f){var l=f("config-requestProvider");l||(l="./xhr");r.getPlatformDefaultId=function(){return"./xhr"};r.load=function(e,d,c,f){q(["platform"==e?"./xhr":l],function(b){c(b)})}})},"dojo/string":function(){define(["./_base/kernel","./_base/lang"],function(r,q){var f=/[&<>'"\/]/g,l={"\x26":"\x26amp;","\x3c":"\x26lt;","\x3e":"\x26gt;",'"':"\x26quot;","'":"\x26#x27;","/":"\x26#x2F;"},e={};q.setObject("dojo.string",
e);e.escape=function(d){return!d?"":d.replace(f,function(c){return l[c]})};e.rep=function(d,c){if(0>=c||!d)return"";for(var e=[];;){c&1&&e.push(d);if(!(c>>=1))break;d+=d}return e.join("")};e.pad=function(d,c,f,b){f||(f="0");d=String(d);c=e.rep(f,Math.ceil((c-d.length)/f.length));return b?d+c:c+d};e.substitute=function(d,c,e,b){b=b||r.global;e=e?q.hitch(b,e):function(a){return a};return d.replace(/\$\{([^\s\:\}]+)(?:\:([^\s\:\}]+))?\}/g,function(a,n,w){a=q.getObject(n,!1,c);w&&(a=q.getObject(w,!1,
b).call(b,a,n));return e(a,n).toString()})};e.trim=String.prototype.trim?q.trim:function(d){d=d.replace(/^\s+/,"");for(var c=d.length-1;0<=c;c--)if(/\S/.test(d.charAt(c))){d=d.substring(0,c+1);break}return d};return e})},"dijit/a11y":function(){define("dojo/_base/array dojo/dom dojo/dom-attr dojo/dom-style dojo/_base/lang dojo/sniff ./main".split(" "),function(r,q,f,l,e,d,c){var h={_isElementShown:function(b){var a=l.get(b);return"hidden"!=a.visibility&&"collapsed"!=a.visibility&&"none"!=a.display&&
"hidden"!=f.get(b,"type")},hasDefaultTabStop:function(b){switch(b.nodeName.toLowerCase()){case "a":return f.has(b,"href");case "area":case "button":case "input":case "object":case "select":case "textarea":return!0;case "iframe":var a;try{var n=b.contentDocument;if("designMode"in n&&"on"==n.designMode)return!0;a=n.body}catch(c){try{a=b.contentWindow.document.body}catch(d){return!1}}return a&&("true"==a.contentEditable||a.firstChild&&"true"==a.firstChild.contentEditable);default:return"true"==b.contentEditable}},
effectiveTabIndex:function(b){return f.get(b,"disabled")?void 0:f.has(b,"tabIndex")?+f.get(b,"tabIndex"):h.hasDefaultTabStop(b)?0:void 0},isTabNavigable:function(b){return 0<=h.effectiveTabIndex(b)},isFocusable:function(b){return-1<=h.effectiveTabIndex(b)},_getTabNavigable:function(b){function a(a){return a&&"input"==a.tagName.toLowerCase()&&a.type&&"radio"==a.type.toLowerCase()&&a.name&&a.name.toLowerCase()}var n,c,v,e,l,s,q={},r=h._isElementShown,x=h.effectiveTabIndex,k=function(b){for(b=b.firstChild;b;b=
b.nextSibling)if(!(1!=b.nodeType||9>=d("ie")&&"HTML"!==b.scopeName||!r(b))){var p=x(b);if(0<=p){if(0==p)n||(n=b),c=b;else if(0<p){if(!v||p<e)e=p,v=b;if(!l||p>=s)s=p,l=b}p=a(b);f.get(b,"checked")&&p&&(q[p]=b)}"SELECT"!=b.nodeName.toUpperCase()&&k(b)}};r(b)&&k(b);return{first:q[a(n)]||n,last:q[a(c)]||c,lowest:q[a(v)]||v,highest:q[a(l)]||l}},getFirstInTabbingOrder:function(b,a){var n=h._getTabNavigable(q.byId(b,a));return n.lowest?n.lowest:n.first},getLastInTabbingOrder:function(b,a){var n=h._getTabNavigable(q.byId(b,
a));return n.last?n.last:n.highest}};e.mixin(c,h);return h})},"dojo/NodeList-manipulate":function(){define("./query ./_base/lang ./_base/array ./dom-construct ./dom-attr ./NodeList-dom".split(" "),function(r,q,f,l,e){function d(b){for(;b.childNodes[0]&&1==b.childNodes[0].nodeType;)b=b.childNodes[0];return b}function c(b,a){"string"==typeof b?(b=l.toDom(b,a&&a.ownerDocument),11==b.nodeType&&(b=b.childNodes[0])):1==b.nodeType&&b.parentNode&&(b=b.cloneNode(!1));return b}var h=r.NodeList;q.extend(h,{_placeMultiple:function(b,
a){for(var n="string"==typeof b||b.nodeType?r(b):b,c=[],d=0;d<n.length;d++)for(var e=n[d],f=this.length,h=f-1,q;q=this[h];h--)0<d&&(q=this._cloneNode(q),c.unshift(q)),h==f-1?l.place(q,e,a):e.parentNode.insertBefore(q,e),e=q;c.length&&(c.unshift(0),c.unshift(this.length-1),Array.prototype.splice.apply(this,c));return this},innerHTML:function(b){return arguments.length?this.addContent(b,"only"):this[0].innerHTML},text:function(b){if(arguments.length){for(var a=0,n;n=this[a];a++)1==n.nodeType&&e.set(n,
"textContent",b);return this}for(var c="",a=0;n=this[a];a++)c+=e.get(n,"textContent");return c},val:function(b){if(arguments.length){for(var a=q.isArray(b),n=0,c;c=this[n];n++){var d=c.nodeName.toUpperCase(),e=c.type,l=a?b[n]:b;if("SELECT"==d){d=c.options;for(e=0;e<d.length;e++){var h=d[e];h.selected=c.multiple?-1!=f.indexOf(b,h.value):h.value==l}}else"checkbox"==e||"radio"==e?c.checked=c.value==l:c.value=l}return this}if((c=this[0])&&1==c.nodeType){b=c.value||"";if("SELECT"==c.nodeName.toUpperCase()&&
c.multiple){b=[];d=c.options;for(e=0;e<d.length;e++)h=d[e],h.selected&&b.push(h.value);b.length||(b=null)}return b}},append:function(b){return this.addContent(b,"last")},appendTo:function(b){return this._placeMultiple(b,"last")},prepend:function(b){return this.addContent(b,"first")},prependTo:function(b){return this._placeMultiple(b,"first")},after:function(b){return this.addContent(b,"after")},insertAfter:function(b){return this._placeMultiple(b,"after")},before:function(b){return this.addContent(b,
"before")},insertBefore:function(b){return this._placeMultiple(b,"before")},remove:h.prototype.orphan,wrap:function(b){if(this[0]){b=c(b,this[0]);for(var a=0,n;n=this[a];a++){var e=this._cloneNode(b);n.parentNode&&n.parentNode.replaceChild(e,n);d(e).appendChild(n)}}return this},wrapAll:function(b){if(this[0]){b=c(b,this[0]);this[0].parentNode.replaceChild(b,this[0]);b=d(b);for(var a=0,n;n=this[a];a++)b.appendChild(n)}return this},wrapInner:function(b){if(this[0]){b=c(b,this[0]);for(var a=0;a<this.length;a++){var n=
this._cloneNode(b);this._wrap(q._toArray(this[a].childNodes),null,this._NodeListCtor).wrapAll(n)}}return this},replaceWith:function(b){b=this._normalize(b,this[0]);for(var a=0,n;n=this[a];a++)this._place(b,n,"before",0<a),n.parentNode.removeChild(n);return this},replaceAll:function(b){b=r(b);for(var a=this._normalize(this,this[0]),n=0,c;c=b[n];n++)this._place(a,c,"before",0<n),c.parentNode.removeChild(c);return this},clone:function(){for(var b=[],a=0;a<this.length;a++)b.push(this._cloneNode(this[a]));
return this._wrap(b,this,this._NodeListCtor)}});h.prototype.html||(h.prototype.html=h.prototype.innerHTML);return h})},"dijit/_WidgetBase":function(){define("require dojo/_base/array dojo/aspect dojo/_base/config dojo/_base/connect dojo/_base/declare dojo/dom dojo/dom-attr dojo/dom-class dojo/dom-construct dojo/dom-geometry dojo/dom-style dojo/has dojo/_base/kernel dojo/_base/lang dojo/on dojo/ready dojo/Stateful dojo/topic dojo/_base/window ./Destroyable dojo/has!dojo-bidi?./_BidiMixin ./registry".split(" "),
function(r,q,f,l,e,d,c,h,b,a,n,w,v,A,t,s,B,C,x,k,z,p,u){function K(a){return function(m){h[m?"set":"remove"](this.domNode,a,m);this._set(a,m)}}v.add("dijit-legacy-requires",!A.isAsync);v.add("dojo-bidi",!1);v("dijit-legacy-requires")&&B(0,function(){r(["dijit/_base/manager"])});var g={};l=d("dijit._WidgetBase",[C,z],{id:"",_setIdAttr:"domNode",lang:"",_setLangAttr:K("lang"),dir:"",_setDirAttr:K("dir"),"class":"",_setClassAttr:{node:"domNode",type:"class"},_setTypeAttr:null,style:"",title:"",tooltip:"",
baseClass:"",srcNodeRef:null,domNode:null,containerNode:null,ownerDocument:null,_setOwnerDocumentAttr:function(a){this._set("ownerDocument",a)},attributeMap:{},_blankGif:l.blankGif||r.toUrl("dojo/resources/blank.gif"),_introspect:function(){var a=this.constructor;if(!a._setterAttrs){var m=a.prototype,g=a._setterAttrs=[],a=a._onMap={},b;for(b in m.attributeMap)g.push(b);for(b in m)/^on/.test(b)&&(a[b.substring(2).toLowerCase()]=b),/^_set[A-Z](.*)Attr$/.test(b)&&(b=b.charAt(4).toLowerCase()+b.substr(5,
b.length-9),(!m.attributeMap||!(b in m.attributeMap))&&g.push(b))}},postscript:function(a,m){this.create(a,m)},create:function(a,m){this._introspect();this.srcNodeRef=c.byId(m);this._connects=[];this._supportingWidgets=[];this.srcNodeRef&&"string"==typeof this.srcNodeRef.id&&(this.id=this.srcNodeRef.id);a&&(this.params=a,t.mixin(this,a));this.postMixInProperties();this.id||(this.id=u.getUniqueId(this.declaredClass.replace(/\./g,"_")),this.params&&delete this.params.id);this.ownerDocument=this.ownerDocument||
(this.srcNodeRef?this.srcNodeRef.ownerDocument:document);this.ownerDocumentBody=k.body(this.ownerDocument);u.add(this);this.buildRendering();var g;if(this.domNode){this._applyAttributes();var b=this.srcNodeRef;b&&(b.parentNode&&this.domNode!==b)&&(b.parentNode.replaceChild(this.domNode,b),g=!0);this.domNode.setAttribute("widgetId",this.id)}this.postCreate();g&&delete this.srcNodeRef;this._created=!0},_applyAttributes:function(){var a={},m;for(m in this.params||{})a[m]=this._get(m);q.forEach(this.constructor._setterAttrs,
function(m){if(!(m in a)){var g=this._get(m);g&&this.set(m,g)}},this);for(m in a)this.set(m,a[m])},postMixInProperties:function(){},buildRendering:function(){this.domNode||(this.domNode=this.srcNodeRef||this.ownerDocument.createElement("div"));if(this.baseClass){var a=this.baseClass.split(" ");this.isLeftToRight()||(a=a.concat(q.map(a,function(a){return a+"Rtl"})));b.add(this.domNode,a)}},postCreate:function(){},startup:function(){this._started||(this._started=!0,q.forEach(this.getChildren(),function(a){!a._started&&
(!a._destroyed&&t.isFunction(a.startup))&&(a.startup(),a._started=!0)}))},destroyRecursive:function(a){this._beingDestroyed=!0;this.destroyDescendants(a);this.destroy(a)},destroy:function(a){function m(m){m.destroyRecursive?m.destroyRecursive(a):m.destroy&&m.destroy(a)}this._beingDestroyed=!0;this.uninitialize();q.forEach(this._connects,t.hitch(this,"disconnect"));q.forEach(this._supportingWidgets,m);this.domNode&&q.forEach(u.findWidgets(this.domNode,this.containerNode),m);this.destroyRendering(a);
u.remove(this.id);this._destroyed=!0},destroyRendering:function(g){this.bgIframe&&(this.bgIframe.destroy(g),delete this.bgIframe);this.domNode&&(g?h.remove(this.domNode,"widgetId"):a.destroy(this.domNode),delete this.domNode);this.srcNodeRef&&(g||a.destroy(this.srcNodeRef),delete this.srcNodeRef)},destroyDescendants:function(a){q.forEach(this.getChildren(),function(m){m.destroyRecursive&&m.destroyRecursive(a)})},uninitialize:function(){return!1},_setStyleAttr:function(a){var m=this.domNode;t.isObject(a)?
w.set(m,a):m.style.cssText=m.style.cssText?m.style.cssText+("; "+a):a;this._set("style",a)},_attrToDom:function(a,m,g){g=3<=arguments.length?g:this.attributeMap[a];q.forEach(t.isArray(g)?g:[g],function(g){var n=this[g.node||g||"domNode"];switch(g.type||"attribute"){case "attribute":t.isFunction(m)&&(m=t.hitch(this,m));g=g.attribute?g.attribute:/^on[A-Z][a-zA-Z]*$/.test(a)?a.toLowerCase():a;n.tagName?h.set(n,g,m):n.set(g,m);break;case "innerText":n.innerHTML="";n.appendChild(this.ownerDocument.createTextNode(m));
break;case "innerHTML":n.innerHTML=m;break;case "class":b.replace(n,m,this[a])}},this)},get:function(a){var m=this._getAttrNames(a);return this[m.g]?this[m.g]():this._get(a)},set:function(a,m){if("object"===typeof a){for(var b in a)this.set(b,a[b]);return this}b=this._getAttrNames(a);var n=this[b.s];if(t.isFunction(n))var c=n.apply(this,Array.prototype.slice.call(arguments,1));else{var n=this.focusNode&&!t.isFunction(this.focusNode)?"focusNode":"domNode",d=this[n]&&this[n].tagName,p;if(p=d)if(!(p=
g[d])){p=this[n];var e={},k;for(k in p)e[k.toLowerCase()]=!0;p=g[d]=e}k=p;b=a in this.attributeMap?this.attributeMap[a]:b.s in this?this[b.s]:k&&b.l in k&&"function"!=typeof m||/^aria-|^data-|^role$/.test(a)?n:null;null!=b&&this._attrToDom(a,m,b);this._set(a,m)}return c||this},_attrPairNames:{},_getAttrNames:function(a){var m=this._attrPairNames;if(m[a])return m[a];var g=a.replace(/^[a-z]|-[a-zA-Z]/g,function(a){return a.charAt(a.length-1).toUpperCase()});return m[a]={n:a+"Node",s:"_set"+g+"Attr",
g:"_get"+g+"Attr",l:g.toLowerCase()}},_set:function(a,g){var b=this[a];this[a]=g;if(this._created&&!(b===g||b!==b&&g!==g))this._watchCallbacks&&this._watchCallbacks(a,b,g),this.emit("attrmodified-"+a,{detail:{prevValue:b,newValue:g}})},_get:function(a){return this[a]},emit:function(a,g,b){g=g||{};void 0===g.bubbles&&(g.bubbles=!0);void 0===g.cancelable&&(g.cancelable=!0);g.detail||(g.detail={});g.detail.widget=this;var n,c=this["on"+a];c&&(n=c.apply(this,b?b:[g]));this._started&&!this._beingDestroyed&&
s.emit(this.domNode,a.toLowerCase(),g);return n},on:function(a,g){var b=this._onMap(a);return b?f.after(this,b,g,!0):this.own(s(this.domNode,a,g))[0]},_onMap:function(a){var g=this.constructor,b=g._onMap;if(!b){var b=g._onMap={},n;for(n in g.prototype)/^on/.test(n)&&(b[n.replace(/^on/,"").toLowerCase()]=n)}return b["string"==typeof a&&a.toLowerCase()]},toString:function(){return"[Widget "+this.declaredClass+", "+(this.id||"NO ID")+"]"},getChildren:function(){return this.containerNode?u.findWidgets(this.containerNode):
[]},getParent:function(){return u.getEnclosingWidget(this.domNode.parentNode)},connect:function(a,g,b){return this.own(e.connect(a,g,this,b))[0]},disconnect:function(a){a.remove()},subscribe:function(a,g){return this.own(x.subscribe(a,t.hitch(this,g)))[0]},unsubscribe:function(a){a.remove()},isLeftToRight:function(){return this.dir?"ltr"==this.dir.toLowerCase():n.isBodyLtr(this.ownerDocument)},isFocusable:function(){return this.focus&&"none"!=w.get(this.domNode,"display")},placeAt:function(g,m){var b=
!g.tagName&&u.byId(g);b&&b.addChild&&(!m||"number"===typeof m)?b.addChild(this,m):(b=b&&"domNode"in b?b.containerNode&&!/after|before|replace/.test(m||"")?b.containerNode:b.domNode:c.byId(g,this.ownerDocument),a.place(this.domNode,b,m),!this._started&&(this.getParent()||{})._started&&this.startup());return this},defer:function(a,g){var b=setTimeout(t.hitch(this,function(){b&&(b=null,this._destroyed||t.hitch(this,a)())}),g||0);return{remove:function(){b&&(clearTimeout(b),b=null);return null}}}});v("dojo-bidi")&&
l.extend(p);return l})},"dojo/touch":function(){define("./_base/kernel ./aspect ./dom ./dom-class ./_base/lang ./on ./has ./mouse ./domReady ./_base/window".split(" "),function(r,q,f,l,e,d,c,h,b,a){function n(a,g,b){return t&&b?function(a,g){return d(a,b,g)}:B?function(b,n){var c=d(b,g,function(a){n.call(this,a);m=(new Date).getTime()}),O=d(b,a,function(a){(!m||(new Date).getTime()>m+1E3)&&n.call(this,a)});return{remove:function(){c.remove();O.remove()}}}:function(g,b){return d(g,a,b)}}function w(a){do if(void 0!==
a.dojoClick)return a;while(a=a.parentNode)}function v(b,m,n){if(!h.isRight(b)){var c=w(b.target);if(x=!b.target.disabled&&c&&c.dojoClick)if(z=(k="useTarget"==x)?c:b.target,k&&b.preventDefault(),p=b.changedTouches?b.changedTouches[0].pageX-a.global.pageXOffset:b.clientX,u=b.changedTouches?b.changedTouches[0].pageY-a.global.pageYOffset:b.clientY,K=("object"==typeof x?x.x:"number"==typeof x?x:0)||4,g=("object"==typeof x?x.y:"number"==typeof x?x:0)||4,!C){C=!0;var e=function(b){x=k?f.isDescendant(a.doc.elementFromPoint(b.changedTouches?
b.changedTouches[0].pageX-a.global.pageXOffset:b.clientX,b.changedTouches?b.changedTouches[0].pageY-a.global.pageYOffset:b.clientY),z):x&&(b.changedTouches?b.changedTouches[0].target:b.target)==z&&Math.abs((b.changedTouches?b.changedTouches[0].pageX-a.global.pageXOffset:b.clientX)-p)<=K&&Math.abs((b.changedTouches?b.changedTouches[0].pageY-a.global.pageYOffset:b.clientY)-u)<=g};a.doc.addEventListener(m,function(a){h.isRight(a)||(e(a),k&&a.preventDefault())},!0);a.doc.addEventListener(n,function(a){if(!h.isRight(a)&&
(e(a),x)){O=(new Date).getTime();var g=k?z:a.target;"LABEL"===g.tagName&&(g=f.byId(g.getAttribute("for"))||g);var b=a.changedTouches?a.changedTouches[0]:a,m=function(g){var m=document.createEvent("MouseEvents");m._dojo_click=!0;m.initMouseEvent(g,!0,!0,a.view,a.detail,b.screenX,b.screenY,b.clientX,b.clientY,a.ctrlKey,a.altKey,a.shiftKey,a.metaKey,0,null);return m},n=m("mousedown"),c=m("mouseup"),p=m("click");setTimeout(function(){d.emit(g,"mousedown",n);d.emit(g,"mouseup",c);d.emit(g,"click",p);O=
(new Date).getTime()},0)}},!0);b=function(g){a.doc.addEventListener(g,function(a){var b=a.target;if(x&&(!a._dojo_click&&(new Date).getTime()<=O+1E3&&!("INPUT"==b.tagName&&l.contains(b,"dijitOffScreen")))&&(a.stopPropagation(),a.stopImmediatePropagation&&a.stopImmediatePropagation(),"click"==g&&("INPUT"!=b.tagName||"radio"==b.type&&(l.contains(b,"dijitCheckBoxInput")||l.contains(b,"mblRadioButton"))||"checkbox"==b.type&&(l.contains(b,"dijitCheckBoxInput")||l.contains(b,"mblCheckBox")))&&"TEXTAREA"!=
b.tagName&&"AUDIO"!=b.tagName&&"VIDEO"!=b.tagName)){var m=null;try{if("A"==b.tagName){for(;(b=b.parentElement)&&!b.classList.contains("dijitMenu")&&!b.classList.contains("dijitButtonNode"););m=b}}catch(n){}m||a.preventDefault()}},!0)};b("click");b("mousedown");b("mouseup")}}}var A=5>c("ios"),t=c("pointer-events")||c("MSPointer"),s=function(){var a={},g;for(g in{down:1,move:1,up:1,cancel:1,over:1,out:1})a[g]=c("MSPointer")?"MSPointer"+g.charAt(0).toUpperCase()+g.slice(1):"pointer"+g;return a}(),B=
c("touch-events"),C,x,k=!1,z,p,u,K,g,O,m,G;c("touch")&&(t?b(function(){a.doc.addEventListener(s.down,function(a){v(a,s.move,s.up)},!0)}):b(function(){function g(a){var b=e.delegate(a,{bubbles:!0});6<=c("ios")&&(b.touches=a.touches,b.altKey=a.altKey,b.changedTouches=a.changedTouches,b.ctrlKey=a.ctrlKey,b.metaKey=a.metaKey,b.shiftKey=a.shiftKey,b.targetTouches=a.targetTouches);return b}G=a.body();a.doc.addEventListener("touchstart",function(a){m=(new Date).getTime();var g=G;G=a.target;d.emit(g,"dojotouchout",
{relatedTarget:G,bubbles:!0});d.emit(G,"dojotouchover",{relatedTarget:g,bubbles:!0});v(a,"touchmove","touchend")},!0);d(a.doc,"touchmove",function(b){m=(new Date).getTime();var n=a.doc.elementFromPoint(b.pageX-(A?0:a.global.pageXOffset),b.pageY-(A?0:a.global.pageYOffset));n&&(G!==n&&(d.emit(G,"dojotouchout",{relatedTarget:n,bubbles:!0}),d.emit(n,"dojotouchover",{relatedTarget:G,bubbles:!0}),G=n),d.emit(n,"dojotouchmove",g(b))||b.preventDefault())});d(a.doc,"touchend",function(b){m=(new Date).getTime();
var n=a.doc.elementFromPoint(b.pageX-(A?0:a.global.pageXOffset),b.pageY-(A?0:a.global.pageYOffset))||a.body();d.emit(n,"dojotouchend",g(b))})}));q={press:n("mousedown","touchstart",s.down),move:n("mousemove","dojotouchmove",s.move),release:n("mouseup","dojotouchend",s.up),cancel:n(h.leave,"touchcancel",t?s.cancel:null),over:n("mouseover","dojotouchover",s.over),out:n("mouseout","dojotouchout",s.out),enter:h._eventHandler(n("mouseover","dojotouchover",s.over)),leave:h._eventHandler(n("mouseout","dojotouchout",
s.out))};return r.touch=q})},"dojo/Stateful":function(){define(["./_base/declare","./_base/lang","./_base/array","./when"],function(r,q,f,l){return r("dojo.Stateful",null,{_attrPairNames:{},_getAttrNames:function(e){var d=this._attrPairNames;return d[e]?d[e]:d[e]={s:"_"+e+"Setter",g:"_"+e+"Getter"}},postscript:function(e){e&&this.set(e)},_get:function(e,d){return"function"===typeof this[d.g]?this[d.g]():this[e]},get:function(e){return this._get(e,this._getAttrNames(e))},set:function(e,d){if("object"===
typeof e){for(var c in e)e.hasOwnProperty(c)&&"_watchCallbacks"!=c&&this.set(c,e[c]);return this}c=this._getAttrNames(e);var f=this._get(e,c);c=this[c.s];var b;"function"===typeof c?b=c.apply(this,Array.prototype.slice.call(arguments,1)):this[e]=d;if(this._watchCallbacks){var a=this;l(b,function(){a._watchCallbacks(e,f,d)})}return this},_changeAttrValue:function(e,d){var c=this.get(e);this[e]=d;this._watchCallbacks&&this._watchCallbacks(e,c,d);return this},watch:function(e,d){var c=this._watchCallbacks;
if(!c)var l=this,c=this._watchCallbacks=function(a,b,d,e){var f=function(c){if(c){c=c.slice();for(var e=0,f=c.length;e<f;e++)c[e].call(l,a,b,d)}};f(c["_"+a]);e||f(c["*"])};!d&&"function"===typeof e?(d=e,e="*"):e="_"+e;var b=c[e];"object"!==typeof b&&(b=c[e]=[]);b.push(d);var a={};a.unwatch=a.remove=function(){var a=f.indexOf(b,d);-1<a&&b.splice(a,1)};return a}})})},"dijit/_base/manager":function(){define(["dojo/_base/array","dojo/_base/config","dojo/_base/lang","../registry","../main"],function(r,
q,f,l,e){var d={};r.forEach("byId getUniqueId findWidgets _destroyAll byNode getEnclosingWidget".split(" "),function(c){d[c]=l[c]});f.mixin(d,{defaultDuration:q.defaultDuration||200});f.mixin(e,d);return e})},"dojo/_base/url":function(){define(["./kernel"],function(r){var q=/^(([^:/?#]+):)?(\/\/([^/?#]*))?([^?#]*)(\?([^#]*))?(#(.*))?$/,f=/^((([^\[:]+):)?([^@]+)@)?(\[([^\]]+)\]|([^\[:]*))(:([0-9]+))?$/,l=function(){for(var e=arguments,d=[e[0]],c=1;c<e.length;c++)if(e[c]){var h=new l(e[c]+""),d=new l(d[0]+
"");if(""==h.path&&!h.scheme&&!h.authority&&!h.query)null!=h.fragment&&(d.fragment=h.fragment),h=d;else if(!h.scheme&&(h.scheme=d.scheme,!h.authority&&(h.authority=d.authority,"/"!=h.path.charAt(0)))){for(var d=(d.path.substring(0,d.path.lastIndexOf("/")+1)+h.path).split("/"),b=0;b<d.length;b++)"."==d[b]?b==d.length-1?d[b]="":(d.splice(b,1),b--):0<b&&(!(1==b&&""==d[0])&&".."==d[b]&&".."!=d[b-1])&&(b==d.length-1?(d.splice(b,1),d[b-1]=""):(d.splice(b-1,2),b-=2));h.path=d.join("/")}d=[];h.scheme&&d.push(h.scheme,
":");h.authority&&d.push("//",h.authority);d.push(h.path);h.query&&d.push("?",h.query);h.fragment&&d.push("#",h.fragment)}this.uri=d.join("");e=this.uri.match(q);this.scheme=e[2]||(e[1]?"":null);this.authority=e[4]||(e[3]?"":null);this.path=e[5];this.query=e[7]||(e[6]?"":null);this.fragment=e[9]||(e[8]?"":null);null!=this.authority&&(e=this.authority.match(f),this.user=e[3]||null,this.password=e[4]||null,this.host=e[6]||e[7],this.port=e[9]||null)};l.prototype.toString=function(){return this.uri};
return r._Url=l})},"dojo/date/stamp":function(){define(["../_base/lang","../_base/array"],function(r,q){var f={};r.setObject("dojo.date.stamp",f);f.fromISOString=function(l,e){f._isoRegExp||(f._isoRegExp=/^(?:(\d{4})(?:-(\d{2})(?:-(\d{2}))?)?)?(?:T(\d{2}):(\d{2})(?::(\d{2})(.\d+)?)?((?:[+-](\d{2}):(\d{2}))|Z)?)?$/);var d=f._isoRegExp.exec(l),c=null;if(d){d.shift();d[1]&&d[1]--;d[6]&&(d[6]*=1E3);e&&(e=new Date(e),q.forEach(q.map("FullYear Month Date Hours Minutes Seconds Milliseconds".split(" "),function(a){return e["get"+
a]()}),function(a,b){d[b]=d[b]||a}));c=new Date(d[0]||1970,d[1]||0,d[2]||1,d[3]||0,d[4]||0,d[5]||0,d[6]||0);100>d[0]&&c.setFullYear(d[0]||1970);var h=0,b=d[7]&&d[7].charAt(0);"Z"!=b&&(h=60*(d[8]||0)+(Number(d[9])||0),"-"!=b&&(h*=-1));b&&(h-=c.getTimezoneOffset());h&&c.setTime(c.getTime()+6E4*h)}return c};f.toISOString=function(f,e){var d=function(a){return 10>a?"0"+a:a};e=e||{};var c=[],h=e.zulu?"getUTC":"get",b="";"time"!=e.selector&&(b=f[h+"FullYear"](),b=["0000".substr((b+"").length)+b,d(f[h+"Month"]()+
1),d(f[h+"Date"]())].join("-"));c.push(b);if("date"!=e.selector){b=[d(f[h+"Hours"]()),d(f[h+"Minutes"]()),d(f[h+"Seconds"]())].join(":");h=f[h+"Milliseconds"]();e.milliseconds&&(b+="."+(100>h?"0":"")+d(h));if(e.zulu)b+="Z";else if("time"!=e.selector)var h=f.getTimezoneOffset(),a=Math.abs(h),b=b+((0<h?"-":"+")+d(Math.floor(a/60))+":"+d(a%60));c.push(b)}return c.join("T")};return f})},"dojo/html":function(){define("./_base/kernel ./_base/lang ./_base/array ./_base/declare ./dom ./dom-construct ./parser".split(" "),
function(r,q,f,l,e,d,c){var h=0,b={_secureForInnerHtml:function(a){return a.replace(/(?:\s*<!DOCTYPE\s[^>]+>|<title[^>]*>[\s\S]*?<\/title>)/ig,"")},_emptyNode:d.empty,_setNodeContent:function(a,b){d.empty(a);if(b)if("string"==typeof b&&(b=d.toDom(b,a.ownerDocument)),!b.nodeType&&q.isArrayLike(b))for(var c=b.length,e=0;e<b.length;e=c==b.length?e+1:0)d.place(b[e],a,"last");else d.place(b,a,"last");return a},_ContentSetter:l("dojo.html._ContentSetter",null,{node:"",content:"",id:"",cleanContent:!1,extractContent:!1,
parseContent:!1,parserScope:r._scopeName,startup:!0,constructor:function(a,b){q.mixin(this,a||{});b=this.node=e.byId(this.node||b);this.id||(this.id=["Setter",b?b.id||b.tagName:"",h++].join("_"))},set:function(a,b){void 0!==a&&(this.content=a);b&&this._mixin(b);this.onBegin();this.setContent();var c=this.onEnd();return c&&c.then?c:this.node},setContent:function(){var a=this.node;if(!a)throw Error(this.declaredClass+": setContent given no node");try{a=b._setNodeContent(a,this.content)}catch(c){var d=
this.onContentError(c);try{a.innerHTML=d}catch(e){}}this.node=a},empty:function(){this.parseDeferred&&(this.parseDeferred.isResolved()||this.parseDeferred.cancel(),delete this.parseDeferred);this.parseResults&&this.parseResults.length&&(f.forEach(this.parseResults,function(a){a.destroy&&a.destroy()}),delete this.parseResults);d.empty(this.node)},onBegin:function(){var a=this.content;if(q.isString(a)&&(this.cleanContent&&(a=b._secureForInnerHtml(a)),this.extractContent)){var c=a.match(/<body[^>]*>\s*([\s\S]+)\s*<\/body>/im);
c&&(a=c[1])}this.empty();this.content=a;return this.node},onEnd:function(){this.parseContent&&this._parse();return this.node},tearDown:function(){delete this.parseResults;delete this.parseDeferred;delete this.node;delete this.content},onContentError:function(a){return"Error occurred setting content: "+a},onExecError:function(a){return"Error occurred executing scripts: "+a},_mixin:function(a){var b={},c;for(c in a)c in b||(this[c]=a[c])},_parse:function(){var a=this.node;try{var b={};f.forEach(["dir",
"lang","textDir"],function(a){this[a]&&(b[a]=this[a])},this);var d=this;this.parseDeferred=c.parse({rootNode:a,noStart:!this.startup,inherited:b,scope:this.parserScope}).then(function(a){return d.parseResults=a},function(a){d._onError("Content",a,"Error parsing in _ContentSette